Pandas là thư viện mở được dùng phổ biến trong ngành phân tích dữ liệu. Hơn thế nữa, nó hỗ trợ bạn thao tác trên dữ liệu bảng.

- Giúp bạn ghi/đọc dữ liệu từ những nguồn tài nguyên khác.
- Làm sạch dữ liệu < loai bo cac phan tu trung lap >
- Truy vấn dữ liệu
-  Gộp và ghép dữ liệu

In [3]:
import numpy as np
import pandas as pd
print(pd.__version__)

2.3.1

- Series: kiểu dữ liệu một chiều
- Index: dùng để biểu thị cho chỉ mục từ những hàng hay cột trong DataFrame.

In [4]:
s = pd.Series([10, 20, 30], index=['a', 'b', 'c'])
print(s)

a    10
b    20
c    30
dtype: int64

DataFrame: kiểu dữ liệu chính trên Pandas và dùng để tượng trưng một bảng dữ liệu

In [5]:
ten = pd.Series(["An", "Binh", "Cuong"])
tuoi = pd.Series([20, 21, 19])

df = pd.DataFrame({
    "Ten": ten,
    "Tuoi": tuoi,
})
print(df)

     Ten  Tuoi
0     An    20
1   Binh    21
2  Cuong    19

In [11]:
s1 = pd.Series({"Ten" : "Duy ", "Tuoi" : 23})
s2 = pd.Series({"Ten" : "Chinh ", "Tuoi" : 24})
df = pd.DataFrame([s1, s2])
print(df)

      Ten  Tuoi
0    Duy     23
1  Chinh     24

In [13]:
data = {
    "Ten" : ["Duy ","Binh", "Cuong"],
    "Tuoi" : [23, 25, 26],
    "Diem" : [10,9,8]
}
df = pd.DataFrame(data)
print(df)

     Ten  Tuoi  Diem
0   Duy     23    10
1   Binh    25     9
2  Cuong    26     8

Đọc file Csv

In [19]:
pf = pd.read_csv(r'C:\Users\Admin\Downloads\Hoc Python\KhoaHocT3H\Titanic.csv')
pf

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.00,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.00,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.00,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,3,0,"Zabour, Miss. Hileni",female,14.50,1,0,2665,14.4542,NaN,C,NaN,328.0,NaN
1305,3,0,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,NaN,NaN,NaN
1306,3,0,"Zakarian, Mr. Mapriededer",male,26.50,0,0,2656,7.2250,NaN,C,NaN,304.0,NaN
1307,3,0,"Zakarian, Mr. Ortin",male,27.00,0,0,2670,7.2250,NaN,C,NaN,NaN,NaN
1308,3,0,"Zimmerman, Mr. Leo",male,29.00,0,0,315082,7.8750,NaN,S,NaN,NaN,NaN

In [35]:
# pf.head(5) # hien thi so dong dau tien mac dinh la 5
# pf.tail(5) # Hien thi so dong cuoi cung
# pf.info() #Thong tin cua file
# pf.describe(include ="all") #Thong ke
# pf.shape # so hang va so cot
# pf.columns # Thong tin hang

In [43]:
# pf["sex"]
# pf["sex"][0]
# pf[["sex","age","ticket"]]
# pf.iloc[0] #truy van hang
pf.loc[0,"name"] # lay gia tri tai hang 0 va chi lay ten

'Allen, Miss. Elisabeth Walton'

Thêm điều kiện tìm kiếm cột

In [58]:
# pf[pf["age"] > 78]
pf[(pf["sex"] == "male") & (pf["age"] > 78)]

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
14,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0,A23,S,B,NaN,"Hessle, Yorks"

Sắp xếp nội dung cột

In [38]:
pf.sort_values("age", ascending=False)
# pf.sort_values(by = "name")

NameError: name 'pf' is not defined

Thêm và xóa cột

In [73]:
pf["is_child"] = pf["age"] > 12
pf = pf.drop(columns="is_child",axis=1)
pf

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.00,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.00,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.00,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,3,0,"Zabour, Miss. Hileni",female,14.50,1,0,2665,14.4542,NaN,C,NaN,328.0,NaN
1305,3,0,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,NaN,NaN,NaN
1306,3,0,"Zakarian, Mr. Mapriededer",male,26.50,0,0,2656,7.2250,NaN,C,NaN,304.0,NaN
1307,3,0,"Zakarian, Mr. Ortin",male,27.00,0,0,2670,7.2250,NaN,C,NaN,NaN,NaN
1308,3,0,"Zimmerman, Mr. Leo",male,29.00,0,0,315082,7.8750,NaN,S,NaN,NaN,NaN

In [93]:
t = pd.read_csv("Titanic.csv") # Doc du lieu

# Thong tin nhanh
# t.head()
# t.shape
# t.info()
# t.describe()
# t.columns

# Truy cap du lieu
# t["name"]
# t[["name", "age"]]
# t.iloc[0]  # Thong tin hang
# t[t["age"] > 30]

In [100]:
# 1. Tạo cột is_child: True nếu Age < 12, ngược lại False
t = pd.read_csv("Titanic.csv")
t["is_child"] = t["age"] < 12

In [112]:
# 2. Lấy hành khách là nam (Sex == 'male') và là trẻ con (is_child == True)
t[(t["sex"] == "male") & (t["is_child"] == True)]

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest,is_child
1,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON",True
54,1,1,"Carter, Master. William Thornton II",male,11.00,1,2,113760,120.0000,B96 B98,S,4,NaN,"Bryn Mawr, PA",True
94,1,1,"Dodge, Master. Washington",male,4.00,0,2,33638,81.8583,A34,S,5,NaN,"San Francisco, CA",True
273,1,1,"Spedden, Master. Robert Douglas",male,6.00,0,2,16966,134.5000,E34,C,3,NaN,"Tuxedo Park, NY",True
339,2,1,"Becker, Master. Richard F",male,1.00,2,1,230136,39.0000,F4,S,11,NaN,"Guntur, India / Benton Harbour, MI",True
359,2,1,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,29.0000,NaN,S,13,NaN,"Bangkok, Thailand / Roseville, IL",True
385,2,1,"Davies, Master. John Morgan Jr",male,8.00,1,1,C.A. 33112,36.7500,NaN,S,14,NaN,"St Ives, Cornwall / Hancock, MI",True
398,2,1,"Drew, Master. Marshall Brines",male,8.00,0,2,28220,32.5000,NaN,S,10,NaN,"Greenport, NY",True
427,2,1,"Hamalainen, Master. Viljo",male,0.67,1,1,250649,14.5000,NaN,S,4,NaN,"Detroit, MI",True
492,2,1,"Mallet, Master. Andre",male,1.00,0,2,S.C./PARIS 2079,37.0042,NaN,C,10,NaN,"Paris / Montreal, PQ",True
514,2,1,"Navratil, Master. Edmond Roger",male,2.00,1,1,230080,26.0000,F2,S,D,NaN,"Nice, France",True
515,2,1,"Navratil, Master. Michel M",male,3.00,1,1,230080,26.0000,F2,S,D,NaN,"Nice, France",True
548,2,1,"Richards, Master. George Sibley",male,0.83,1,1,29106,18.7500,NaN,S,4,NaN,"Cornwall / Akron, OH",True
549,2,1,"Richards, Master. William Rowe",male,3.00,1,1,29106,18.7500,NaN,S,4,NaN,"Cornwall / Akron, OH",True
587,2,1,"Wells, Master. Ralph Lester",male,2.00,1,1,29103,23.0000,NaN,S,14,NaN,"Cornwall / Akron, OH",True
611,3,1,"Aks, Master. Philip Frank",male,0.83,0,1,392091,9.3500,NaN,S,11,NaN,"London, England Norfolk, VA",True
622,3,0,"Andersson, Master. Sigvard Harald Elias",male,4.00,4,2,347082,31.2750,NaN,S,NaN,NaN,"Sweden Winnipeg, MN",True
639,3,0,"Asplund, Master. Carl Edgar",male,5.00,4,2,347077,31.3875,NaN,S,NaN,NaN,"Sweden Worcester, MA",True
640,3,0,"Asplund, Master. Clarence Gustaf Hugo",male,9.00,4,2,347077,31.3875,NaN,S,NaN,NaN,"Sweden Worcester, MA",True
641,3,1,"Asplund, Master. Edvin Rojj Felix",male,3.00,4,2,347077,31.3875,NaN,S,15,NaN,"Sweden Worcester, MA",True
678,3,0,"Boulos, Master. Akar",male,6.00,1,1,2678,15.2458,NaN,C,NaN,NaN,"Syria Kent, ON",True
733,3,1,"Coutts, Master. Eden Leslie ""Neville""",male,9.00,1,1,C.A. 37671,15.9000,NaN,S,2,NaN,"England Brooklyn, NY",True
734,3,1,"Coutts, Master. William Loch ""William""",male,3.00,1,1,C.A. 37671,15.9000,NaN,S,2,NaN,"England Brooklyn, NY",True
747,3,0,"Danbom, Master. Gilbert Sigvard Emanuel",male,0.33,0,2,347080,14.4000,NaN,S,NaN,NaN,"Stanton, IA",True
762,3,1,"Dean, Master. Bertram Vere",male,1.00,1,2,C.A. 2315,20.5750,NaN,S,10,NaN,"Devon, England Wichita, KS",True
820,3,1,"Goldsmith, Master. Frank John William ""Frankie""",male,9.00,0,2,363291,20.5250,NaN,S,C D,NaN,"Strood, Kent, England Detroit, MI",True
825,3,0,"Goodwin, Master. Harold Victor",male,9.00,5,2,CA 2144,46.9000,NaN,S,NaN,NaN,"Wiltshire, England Niagara Falls, NY",True
826,3,0,"Goodwin, Master. Sidney Leonard",male,1.00,5,2,CA 2144,46.9000,NaN,S,NaN,NaN,"Wiltshire, England Niagara Falls, NY",True
827,3,0,"Goodwin, Master. William Frederick",male,11.00,5,2,CA 2144,46.9000,NaN,S,NaN,NaN,"Wiltshire, England Niagara Falls, NY",True
855,3,0,"Hassan, Mr. Houssein G N",male,11.00,0,0,2699,18.7875,NaN,C,NaN,NaN,NaN,True
894,3,1,"Johnson, Master. Harold Theodor",male,4.00,1,1,347742,11.1333,NaN,S,15,NaN,NaN,True
1025,3,1,"Moor, Master. Meier",male,6.00,0,1,392096,12.4750,E121,S,14,NaN,NaN,True
1082,3,1,"Olsen, Master. Artur Karl",male,9.00,0,1,C 17368,3.1708,NaN,S,13,NaN,NaN,True
1096,3,0,"Palsson, Master. Gosta Leonard",male,2.00,3,1,349909,21.0750,NaN,S,NaN,4.0,NaN,True
1097,3,0,"Palsson, Master. Paul Folke",male,6.00,3,1,349909,21.0750,NaN,S,NaN,NaN,NaN,True
1101,3,0,"Panula, Master. Eino Viljami",male,1.00,4,1,3101295,39.6875,NaN,S,NaN,NaN,NaN,True
1102,3,0,"Panula, Master. Juha Niilo",male,7.00,4,1,3101295,39.6875,NaN,S,NaN,NaN,NaN,True
1103,3,0,"Panula, Master. Urho Abraham",male,2.00,4,1,3101295,39.6875,NaN,S,NaN,NaN,NaN,True
1111,3,0,"Peacock, Master. Alfred Edward",male,0.75,1,1,SOTON/O.Q. 3101315,13.7750,NaN,S,NaN,NaN,NaN,True
1141,3,0,"Rice, Master. Albert",male,10.00,4,1,382652,29.1250,NaN,Q,NaN,NaN,NaN,True
1142,3,0,"Rice, Master. Arthur",male,4.00,4,1,382652,29.1250,NaN,Q,NaN,NaN,NaN,True
1143,3,0,"Rice, Master. Eric",male,7.00,4,1,382652,29.1250,NaN,Q,NaN,NaN,NaN,True
1144,3,0,"Rice, Master. Eugene",male,2.00,4,1,382652,29.1250,NaN,Q,NaN,NaN,NaN,True
1145,3,0,"Rice, Master. George Hugh",male,8.00,4,1,382652,29.1250,NaN,Q,NaN,NaN,NaN,True
1206,3,0,"Skoog, Master. Harald",male,4.00,3,2,347088,27.9000,NaN,S,NaN,NaN,NaN,True
1207,3,0,"Skoog, Master. Karl Thorsten",male,10.00,3,2,347088,27.9000,NaN,S,NaN,NaN,NaN,True
1240,3,1,"Thomas, Master. Assad Alexander",male,0.42,0,1,2625,8.5167,NaN,C,16,NaN,NaN,True
1256,3,1,"Touma, Master. Georges Youssef",male,7.00,1,1,2650,15.2458,NaN,C,C,NaN,NaN,True
1263,3,0,"van Billiard, Master. Walter John",male,11.50,1,1,A/5. 851,14.5000,NaN,S,NaN,1.0,NaN,True

In [113]:
# 3. Lấy tất cả hành khách > 60 tuổi
t[t["age"] > 60 ]

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest,is_child
6,1,1,"Andrews, Miss. Kornelia Theodosia",female,63.0,1,0,13502,77.9583,D7,S,10,NaN,"Hudson, NY",False
9,1,0,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C,NaN,22.0,"Montevideo, Uruguay",False
14,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S,B,NaN,"Hessle, Yorks",False
61,1,1,"Cavendish, Mrs. Tyrell William (Julia Florence...",female,76.0,1,0,19877,78.8500,C46,S,6,NaN,"Little Onn Hall, Staffs",False
78,1,1,"Compton, Mrs. Alexander Taylor (Mary Eliza Ing...",female,64.0,0,2,PC 17756,83.1583,E45,C,14,NaN,"Lakewood, NJ",False
81,1,0,"Crosby, Capt. Edward Gifford",male,70.0,1,1,WE/P 5735,71.0000,B22,S,NaN,269.0,"Milwaukee, WI",False
83,1,1,"Crosby, Mrs. Edward Gifford (Catherine Elizabe...",female,64.0,1,1,112901,26.5500,B26,S,7,NaN,"Milwaukee, WI",False
115,1,0,"Fortune, Mr. Mark",male,64.0,1,4,19950,263.0000,C23 C25 C27,S,NaN,NaN,"Winnipeg, MB",False
135,1,0,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C,NaN,NaN,"New York, NY",False
205,1,0,"Millet, Mr. Francis Davis",male,65.0,0,0,13509,26.5500,E38,S,NaN,249.0,"East Bridgewater, MA",False
217,1,0,"Nicholson, Mr. Arthur Ernest",male,64.0,0,0,693,26.0000,NaN,S,NaN,263.0,"Isle of Wight, England",False
221,1,0,"Ostby, Mr. Engelhart Cornelius",male,65.0,0,1,113509,61.9792,B30,C,NaN,234.0,"Providence, RI",False
252,1,0,"Ryerson, Mr. Arthur Larned",male,61.0,1,3,PC 17608,262.3750,B57 B59 B63 B66,C,NaN,NaN,"Haverford, PA / Cooperstown, NY",False
279,1,0,"Stead, Mr. William Thomas",male,62.0,0,0,113514,26.5500,C87,S,NaN,NaN,"Wimbledon Park, London / Hayling Island, Hants",False
284,1,1,"Stone, Mrs. George Nelson (Martha Evelyn)",female,62.0,0,0,113572,80.0000,B28,NaN,6,NaN,"Cincinatti, OH",False
285,1,0,"Straus, Mr. Isidor",male,67.0,1,0,PC 17483,221.7792,C55 C57,S,NaN,96.0,"New York, NY",False
286,1,0,"Straus, Mrs. Isidor (Rosalie Ida Blun)",female,63.0,1,0,PC 17483,221.7792,C55 C57,S,NaN,NaN,"New York, NY",False
287,1,0,"Sutton, Mr. Frederick",male,61.0,0,0,36963,32.3208,D50,S,NaN,46.0,"Haddenfield, NJ",False
300,1,0,"Van der hoef, Mr. Wyckoff",male,61.0,0,0,111240,33.5000,B19,S,NaN,245.0,"Brooklyn, NY",False
303,1,0,"Warren, Mr. Frank Manley",male,64.0,1,0,110813,75.2500,D37,C,NaN,NaN,"Portland, OR",False
321,1,0,"Wright, Mr. George",male,62.0,0,0,113807,26.5500,NaN,S,NaN,NaN,"Halifax, NS",False
432,2,1,"Harris, Mr. George",male,62.0,0,0,S.W./PP 752,10.5000,NaN,S,15,NaN,London,False
455,2,0,"Howard, Mr. Benjamin",male,63.0,1,0,24065,26.0000,NaN,S,NaN,NaN,"Swindon, England",False
487,2,0,"Lingane, Mr. John",male,61.0,0,0,235509,12.3500,NaN,Q,NaN,NaN,NaN,False
506,2,0,"Mitchell, Mr. Henry Michael",male,70.0,0,0,C.A. 24580,10.5000,NaN,S,NaN,NaN,"Guernsey / Montclair, NJ and/or Toledo, Ohio",False
511,2,0,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q,NaN,NaN,"Cambridge, MA",False
594,2,0,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,NaN,S,NaN,NaN,"Guernsey, England / Edgewood, RI",False
727,3,0,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q,NaN,171.0,NaN,False
782,3,0,"Duane, Mr. Frank",male,65.0,0,0,336439,7.7500,NaN,Q,NaN,NaN,NaN,False
1068,3,0,"Nysveen, Mr. Johan Hansen",male,61.0,0,0,345364,6.2375,NaN,S,NaN,NaN,NaN,False
1225,3,0,"Storey, Mr. Thomas",male,60.5,0,0,3701,NaN,NaN,S,NaN,261.0,NaN,False
1235,3,0,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S,NaN,NaN,NaN,False
1261,3,1,"Turkula, Mrs. (Hedwig)",female,63.0,0,0,4134,9.5875,NaN,S,15,NaN,NaN,False

In [156]:
# 4. Tính trung bình độ tuổi của hành khách (không tính giá trị thiếu)
# Thay thế NaN bằng giá trị trung bình
# Tính tuổi trung bình (bỏ qua NaN)
# t.fillna(0)
t = pd.read_csv("Titanic.csv")
mean = t['age'].mean()
t['age'] =t["age"].fillna(mean)
t

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.000000,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.920000,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2.000000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.000000,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.000000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,3,0,"Zabour, Miss. Hileni",female,14.500000,1,0,2665,14.4542,NaN,C,NaN,328.0,NaN
1305,3,0,"Zabour, Miss. Thamine",female,29.881138,1,0,2665,14.4542,NaN,C,NaN,NaN,NaN
1306,3,0,"Zakarian, Mr. Mapriededer",male,26.500000,0,0,2656,7.2250,NaN,C,NaN,304.0,NaN
1307,3,0,"Zakarian, Mr. Ortin",male,27.000000,0,0,2670,7.2250,NaN,C,NaN,NaN,NaN
1308,3,0,"Zimmerman, Mr. Leo",male,29.000000,0,0,315082,7.8750,NaN,S,NaN,NaN,NaN

In [157]:
# 5. Đếm số lượng hành khách theo giới tính
t['sex'].value_counts()

sex
male      843
female    466
Name: count, dtype: int64

In [158]:
# 6. Tìm hành khách ở tầng vé hạng nhất (Pclass == 1) và tuổi < 18
t[(t["pclass"] == 1) & (t["age"] < 18)]

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
1,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
53,1,0,"Carrau, Mr. Jose Pedro",male,17.00,0,0,113059,47.1000,NaN,S,NaN,NaN,"Montevideo, Uruguay"
54,1,1,"Carter, Master. William Thornton II",male,11.00,1,2,113760,120.0000,B96 B98,S,4,NaN,"Bryn Mawr, PA"
55,1,1,"Carter, Miss. Lucile Polk",female,14.00,1,2,113760,120.0000,B96 B98,S,4,NaN,"Bryn Mawr, PA"
92,1,1,"Dick, Mrs. Albert Adrian (Vera Gillespie)",female,17.00,1,0,17474,57.0000,B20,S,3,NaN,"Calgary, AB"
94,1,1,"Dodge, Master. Washington",male,4.00,0,2,33638,81.8583,A34,S,5,NaN,"San Francisco, CA"
159,1,1,"Hippach, Miss. Jean Gertrude",female,16.00,0,1,111361,57.9792,B18,C,4,NaN,"Chicago, IL"
187,1,1,"Lines, Miss. Mary Conover",female,16.00,0,1,PC 17592,39.4000,D28,S,9,NaN,"Paris, France"
193,1,1,"Madill, Miss. Georgette Alexandra",female,15.00,0,1,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
195,1,1,"Maioni, Miss. Roberta",female,16.00,0,0,110152,86.5000,B79,S,8,NaN,NaN
229,1,1,"Penasco y Castellana, Mrs. Victor de Satode (M...",female,17.00,1,0,PC 17758,108.9000,C65,C,8,NaN,"Madrid, Spain"
249,1,1,"Ryerson, Master. John Borie",male,13.00,2,2,PC 17608,262.3750,B57 B59 B63 B66,C,4,NaN,"Haverford, PA / Cooperstown, NY"
273,1,1,"Spedden, Master. Robert Douglas",male,6.00,0,2,16966,134.5000,E34,C,3,NaN,"Tuxedo Park, NY"
295,1,1,"Thayer, Mr. John Borland Jr",male,17.00,0,2,17421,110.8833,C70,C,B,NaN,"Haverford, PA"

In [160]:
# 7. Tính số lượng hành khách ở mỗi hạng vé (Pclass)
t['pclass'].value_counts()

pclass
3    709
1    323
2    277
Name: count, dtype: int64

In [173]:
# 8. Tính tỷ lệ sống sót (survived) theo từng hạng vé (pclass)
# a = t[(t["pclass"] == 1) & (t["survived"] == 1)]
# a['pclass'].value_counts()
#
# mean = a["count"] / t["count"]
t.groupby("pclass")["survived"].mean()

pclass
1    0.619195
2    0.429603
3    0.255289
Name: survived, dtype: float64

In [175]:
# 9. Tính tuổi trung bình theo giới tính
t.groupby("sex")["age"].mean()

sex
female    28.886950
male      30.430712
Name: age, dtype: float64

In [183]:
import pandas as pd

t.groupby(["pclass", "sex", "survived"]).size()

pclass  sex     survived
1       female  0             5
                1           139
        male    0           118
                1            61
2       female  0            12
                1            94
        male    0           146
                1            25
3       female  0           110
                1           106
        male    0           418
                1            75
dtype: int64

In [ ]:
# 1. Thêm cột FamilySize = SibSp + Parch
#  2. Thêm cột IsAlone:
# Nếu FamilySize == 0 thì là 1 (đi một mình),
#
# Ngược lại là 0.
# 3. Tách họ (LastName) từ cột Name và lưu vào cột LastName

# Cột Name có dạng: "LastName, Title Firstname"
# Dùng split để lấy phần trước dấu ","

In [26]:
import pandas as pd

file = pd.read_csv("Titanic.csv")
# 1. Thêm cột FamilySize = SibSp + Parch
file["FamilySize"] = file["sibsp"] + file["parch"]
#  2. Thêm cột IsAlone:
# Nếu FamilySize == 0 thì là 1 (đi một mình),
# Ngược lại là 0.
file["IsAlone"] =(file["FamilySize"] == 0).astype(int)

# 3. Tách họ (LastName) từ cột Name và lưu vào cột LastName
# Cột Name có dạng: "LastName, Title Firstname"
# Dùng split để lấy phần trước dấu ","
file["LastName"] = file["name"].str.split(",", n=1, expand= True)[0]
file

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest,FamilySize,IsAlone,LastName
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.00,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO",0,1,Allen
1,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON",3,0,Allison
2,1,0,"Allison, Miss. Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON",3,0,Allison
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.00,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON",3,0,Allison
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.00,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON",3,0,Allison
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,3,0,"Zabour, Miss. Hileni",female,14.50,1,0,2665,14.4542,NaN,C,NaN,328.0,NaN,1,0,Zabour
1305,3,0,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,NaN,NaN,NaN,1,0,Zabour
1306,3,0,"Zakarian, Mr. Mapriededer",male,26.50,0,0,2656,7.2250,NaN,C,NaN,304.0,NaN,0,1,Zakarian
1307,3,0,"Zakarian, Mr. Ortin",male,27.00,0,0,2670,7.2250,NaN,C,NaN,NaN,NaN,0,1,Zakarian
1308,3,0,"Zimmerman, Mr. Leo",male,29.00,0,0,315082,7.8750,NaN,S,NaN,NaN,NaN,0,1,Zimmerman